import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import NavbarLinks from "@/components/NavbarLinks";
import Link from "next/link";
import Footer from "@/components/Footer";
import Brand from "@/components/Brand";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-lux-serif",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable} antialiased`}>
        <Providers>
          <header className="sticky top-0 z-50 nav-blur border-b border-black/10">
            <nav className="container flex items-center justify-between py-3">
              <Brand />
              <NavbarLinks />
            </nav>
          </header>
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
